# Generated by Django 4.1.7 on 2023-03-08 08:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDocument',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('company_id', jsonfield.fields.JSONField(null=True)),
                ('created_by', jsonfield.fields.JSONField(null=True)),
                ('eventId', jsonfield.fields.JSONField(null=True)),
                ('page', jsonfield.fields.JSONField(null=True)),
                ('auth_user_list', jsonfield.fields.JSONField(null=True)),
                ('content', jsonfield.fields.JSONField(null=True)),
                ('created_on', jsonfield.fields.JSONField(null=True)),
                ('document_name', jsonfield.fields.JSONField(null=True)),
                ('reject_message', jsonfield.fields.JSONField(null=True)),
                ('rejected_by', jsonfield.fields.JSONField(null=True)),
                ('state', jsonfield.fields.JSONField(null=True)),
                ('update_time', jsonfield.fields.JSONField(null=True)),
                ('workflow_id', jsonfield.fields.JSONField(null=True)),
                ('workflow_process', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTemplte',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('company_id', jsonfield.fields.JSONField(null=True)),
                ('content', jsonfield.fields.JSONField(null=True)),
                ('created_by', jsonfield.fields.JSONField(null=True)),
                ('created_on', jsonfield.fields.JSONField(null=True)),
                ('data_type', jsonfield.fields.JSONField(null=True)),
                ('eventId', jsonfield.fields.JSONField(null=True)),
                ('page', jsonfield.fields.JSONField(null=True)),
                ('template_name', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteWorkflow',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('company_id', jsonfield.fields.JSONField(null=True)),
                ('created_by', jsonfield.fields.JSONField(null=True)),
                ('eventId', jsonfield.fields.JSONField(null=True)),
                ('workflows', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
