# Generated by Django 4.1.7 on 2023-03-22 06:18

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDocument',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('document_name', jsonfield.fields.JSONField()),
                ('company_id', jsonfield.fields.JSONField()),
                ('favourited_by', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTemplate',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('company_id', jsonfield.fields.JSONField()),
                ('template_name', jsonfield.fields.JSONField()),
                ('favourited_by', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteWorkflow',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('company_id', jsonfield.fields.JSONField()),
                ('workflows', jsonfield.fields.JSONField()),
                ('favourited_by', models.TextField(max_length=200)),
            ],
        ),
    ]
