# Generated by Django 4.1.7 on 2023-03-15 07:48

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritedocument",
            name="username",
            field=models.TextField(
                default=jsonfield.fields.JSONField(null=True), max_length=200
            ),
        ),
        migrations.AddField(
            model_name="favoritetemplate",
            name="username",
            field=models.TextField(
                default=jsonfield.fields.JSONField(null=True), max_length=200
            ),
        ),
        migrations.AddField(
            model_name="favoriteworkflow",
            name="username",
            field=models.TextField(
                default=jsonfield.fields.JSONField(null=True), max_length=200
            ),
        ),
    ]
