# Generated by Django 4.1.7 on 2023-03-21 12:55

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritedocument',
            name='auth_user_list',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='content',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='page',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='reject_message',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='state',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='workflow_id',
        ),
        migrations.RemoveField(
            model_name='favoritedocument',
            name='workflow_process',
        ),
        migrations.RemoveField(
            model_name='favoritetemplate',
            name='content',
        ),
        migrations.RemoveField(
            model_name='favoritetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='favoritetemplate',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='favoritetemplate',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='favoritetemplate',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='favoritetemplate',
            name='page',
        ),
        migrations.RemoveField(
            model_name='favoriteworkflow',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='favoriteworkflow',
            name='eventId',
        ),
        migrations.AddField(
            model_name='favoritedocument',
            name='favourited_by',
            field=models.TextField(default='User', max_length=200),
        ),
        migrations.AddField(
            model_name='favoritetemplate',
            name='favourited_by',
            field=models.TextField(default='User', max_length=200),
        ),
        migrations.AddField(
            model_name='favoriteworkflow',
            name='favourited_by',
            field=models.TextField(default='User', max_length=200),
        ),
        migrations.AlterField(
            model_name='favoritedocument',
            name='company_id',
            field=jsonfield.fields.JSONField(default='Company'),
        ),
        migrations.AlterField(
            model_name='favoritedocument',
            name='document_name',
            field=jsonfield.fields.JSONField(default='Document'),
        ),
        migrations.AlterField(
            model_name='favoritetemplate',
            name='company_id',
            field=jsonfield.fields.JSONField(default='Company'),
        ),
        migrations.AlterField(
            model_name='favoritetemplate',
            name='template_name',
            field=jsonfield.fields.JSONField(default='Template'),
        ),
        migrations.AlterField(
            model_name='favoriteworkflow',
            name='company_id',
            field=jsonfield.fields.JSONField(default='Company'),
        ),
        migrations.AlterField(
            model_name='favoriteworkflow',
            name='workflows',
            field=jsonfield.fields.JSONField(default='Workflows'),
        ),
    ]
