# Generated by Django 4.1.7 on 2023-03-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_favoritedocument_username_favoritetemplate_username_and_more"),
        ("app", "0002_remove_favoritedocument_auth_user_list_and_more"),
    ]

    operations = []
