# Generated by Django 4.1.7 on 2024-01-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_processreminder_favoritedocument_collection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processreminder',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processreminder',
            name='_id',
            field=models.TextField(),
        ),
    ]
