# Generated by Django 4.1.7 on 2024-01-31 16:45

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_processreminder_id_alter_processreminder__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processreminder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processreminder',
            name='process_created_by',
        ),
        migrations.AddField(
            model_name='processreminder',
            name='created_by',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='processreminder',
            name='interval',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='processreminder',
            name='process_email',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='processreminder',
            name='_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processreminder',
            name='last_reminder_datetime',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
