# Generated by Django 4.1.7 on 2024-01-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_processreminder_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processreminder',
            old_name='created_by',
            new_name='collection_id',
        ),
        migrations.RenameField(
            model_name='processreminder',
            old_name='interval',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='processreminder',
            old_name='last_reminder_datetime',
            new_name='document_name',
        ),
        migrations.RemoveField(
            model_name='processreminder',
            name='process_email',
        ),
        migrations.AddField(
            model_name='processreminder',
            name='favourited_by',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
