# Generated by Django 4.1.7 on 2024-01-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_created_by_processreminder_collection_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processreminder',
            old_name='favourited_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='processreminder',
            old_name='collection_id',
            new_name='interval',
        ),
        migrations.RenameField(
            model_name='processreminder',
            old_name='company_id',
            new_name='last_reminder_datetime',
        ),
        migrations.RenameField(
            model_name='processreminder',
            old_name='document_name',
            new_name='process_email',
        ),
    ]
