# Generated by Django 4.1.7 on 2024-01-31 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_favourited_by_processreminder_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processreminder',
            old_name='process_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='processreminder',
            name='process_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processreminder',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
