# Generated by Django 4.1.7 on 2024-02-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_process_email_processreminder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processreminder',
            name='step_finalizer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
