# Generated by Django 4.2.3 on 2024-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDocument',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('document_name', models.JSONField()),
                ('company_id', models.JSONField()),
                ('collection_id', models.JSONField()),
                ('favourited_by', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTemplate',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('company_id', models.JSONField()),
                ('collection_id', models.JSONField()),
                ('template_name', models.JSONField()),
                ('favourited_by', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteWorkflow',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('company_id', models.JSONField()),
                ('workflows', models.JSONField()),
                ('favourited_by', models.TextField(max_length=200)),
            ],
        ),
    ]
